name: Playwright Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: "0 11 * * 1,3"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      EMP_CODE: ${{ secrets.EMP_CODE }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project=chromium
      - name: current working directory files
        run: sudo ls 
      - name: Install Allure command-line tool
        run: |
              wget -O allure-2.14.0.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.tgz
              tar -zxvf allure-2.14.0.tgz -C /opt/
              sudo ln -s /opt/allure-2.14.0/bin/allure /usr/bin/allure   
      - name: Generate Allure report
        run: |
           allure generate allure-results --clean -o allure-report
      - name: Install mailx
        run: sudo apt-get update && sudo apt-get install -y mailutils  
      - name : send mail
        run :  echo "This is the body of the email." |  mailx  -A  allure-report/index.html  - s "A mail sent using mailx" hariprasathk14@gmail.com 

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java 
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      # - name: Install Allure command-line tool
      #   run: |
      #         wget -O allure-2.14.0.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.tgz
      #         tar -zxvf allure-2.14.0.tgz -C /opt/
      #         sudo ln -s /opt/allure-2.14.0/bin/allure /usr/bin/allure
      - name: Print current working directory files
        run: sudo ls      
        
      # - name: Generate Allure report
      #   run: |
      # #     allure generate allure-results --clean -o allure-report
      # - name: Install mailx
      #   run: sudo apt-get update && sudo apt-get install -y mailutils  
      
    
